### ISSUE TITLE
BagaturChess - large log

### ISSUE THREAD

**Issue by yellow-panther** [bagaturchess/Bagatur-Chess-Engine-And-Tools#1]
Roman Koldaev https://sourceforge.net/p/sjce/ said: Added cleaner for Bagatur's large log

He created the SJCE interface https://sourceforge.net/projects/sjce/ for WB/UCI compatible chess engines written in Java

harp07@mail.ru is his email-address (for further questions)

**Comment by bagaturchess** [comment]
Hi Roman,
have you tried the newest version of Bagatur (1.4b)?I wander whether there is the same issue with the log files ...
Best Regards,Krasimir 

    On Thursday, June 16, 2016 12:08 PM, yellow-panther <notifications@github.com> wrote:
 

 Roman Koldaev https://sourceforge.net/p/sjce/ said: Added cleaner for Bagatur's large logHe created the SJCE interface https://sourceforge.net/projects/sjce/ for WB/UCI compatible chess engines written in Javaharp07@mail.ru is his email-address (for further questions)—

**Comment by bagaturchess** [comment]
Fixed in the latest version
