### ISSUE TITLE
Google website of Bagatur Chess

### ISSUE THREAD

**Issue by ChessGUI** [bagaturchess/Bagatur-Chess-Engine-And-Tools#2]
Hello,

Günther pointed out on http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=720119&t=63986 that your engine disappeared from Google.

Only a coincidence or is Bagatur Chess on Google an obsolete website?

**Comment by bagaturchess** [comment]
Hello,yes, the website is not valid anymore it contains irrelevant information.The only source now is github project.Best Regards,Krasimir 

    On Saturday, June 24, 2017 8:23 AM, ChessGUI <notifications@github.com> wrote:
 

 Hello,Günther pointed out on http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=720119&t=63986 that your engine disappeared from Google.Only a coincidence or is Bagatur Chess on Google an obsolete website?—

**Comment by bagaturchess** [comment]
Hello Friends,
yes, the site is obsolete. It contains irrelevant information.
Best Regards,
Krasimir
